pub mod agent;
mod auth;
mod authz;
mod config;
mod connection;
pub mod cron;
mod debug_bytes;
mod execpolicy;
mod homie_config;
pub mod jobs;
pub mod notifications;
mod outbound;
pub mod pairing;
mod paths;
pub mod presence;
pub mod router;
mod server;
pub mod storage;
pub mod terminal;

pub use agent::{AgentService, ChatService};
pub use auth::{AuthOutcome, LiveWhois, TailscaleIdentity, TailscaleWhois};
pub use authz::{context_for_outcome, scope_for_method, AuthContext, Role, Scope};
pub use config::ServerConfig;
pub use connection::Connection;
pub use cron::CronService;
pub use execpolicy::ExecPolicy;
pub use homie_config::HomieConfig;
pub use jobs::JobsService;
pub use notifications::NotificationsService;
pub use outbound::OutboundMessage;
pub use pairing::PairingService;
pub use router::{MessageRouter, ServiceHandler, ServiceRegistry, SubscriptionManager};
pub use server::build_router;
pub use storage::{ChatRecord, SessionStatus, SqliteStore, Store, TerminalRecord};
pub use terminal::TerminalService;
